# AUGMENTATION: True
# IMAGE_SIZE: [224,224,3]
# BATCH_SIZE : 16
# INCLUDE_TOP: False
# EPOCHS: 10
# CLASSES: 2
# WEIGHTS: imagenet
# LEARNING_RATE: 0.01

IMAGE_SIZE: [299, 299, 3]
INCLUDE_TOP: False
WEIGHTS: imagenet
LEARNING_RATE: 0.01  # better than 0.01 for transfer learning
CLASSES: 2
BATCH_SIZE : 16
EPOCHS: 1
AUGMENTATION: True